/**
 * Server API Client
 * サーバー経由が必要なAPI（DB、秘密キー必要なもの）
 */

import { syncStorage } from '../chrome-storage';

interface Settings {
  apiBaseUrl: string;
}

async function getApiBaseUrl(): Promise<string> {
  const settings = await syncStorage.get<Settings>('settings');
  return settings?.apiBaseUrl || 'http://localhost:3001';
}

// ============================================
// Study Logs API
// ============================================

export interface StudyLog {
  id?: string;
  url: string;
  domain: string;
  pageTitle: string;
  duration: number;
  startedAt: string;
  endedAt: string;
  notes?: string;
}

/**
 * 学習ログを保存
 */
export async function saveStudyLog(log: Omit<StudyLog, 'id'>): Promise<{ success: boolean; id?: string; error?: string }> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/study-logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(log),
    });

    if (!response.ok) {
      throw new Error(`Failed to save study log: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, id: data.id };
  } catch (error) {
    console.error('Failed to save study log:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * 学習ログを取得
 */
export async function getStudyLogs(params?: {
  limit?: number;
  offset?: number;
  startDate?: string;
  endDate?: string;
}): Promise<{ success: boolean; data?: StudyLog[]; error?: string }> {
  try {
    const baseUrl = await getApiBaseUrl();
    const searchParams = new URLSearchParams();

    if (params?.limit) searchParams.set('limit', params.limit.toString());
    if (params?.offset) searchParams.set('offset', params.offset.toString());
    if (params?.startDate) searchParams.set('startDate', params.startDate);
    if (params?.endDate) searchParams.set('endDate', params.endDate);

    const url = `${baseUrl}/api/study-logs${searchParams.toString() ? `?${searchParams}` : ''}`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to fetch study logs: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, data: data.data || [] };
  } catch (error) {
    console.error('Failed to fetch study logs:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// YouTube Captions API
// ============================================

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface CaptionEntry {
  start: number;
  duration: number;
  text: string;
}

/**
 * YouTube動画の字幕トラック一覧を取得
 */
export async function getCaptionTracks(videoId: string): Promise<{
  success: boolean;
  tracks?: CaptionTrack[];
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/captions/${videoId}`);

    if (!response.ok) {
      throw new Error(`Failed to fetch captions: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, tracks: data.tracks };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * YouTube動画の字幕を取得
 */
export async function getCaptions(
  videoId: string,
  languageCode?: string
): Promise<{
  success: boolean;
  captions?: CaptionEntry[];
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const url = languageCode
      ? `${baseUrl}/api/captions/${videoId}?lang=${languageCode}`
      : `${baseUrl}/api/captions/${videoId}`;

    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to fetch captions: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, captions: data.captions };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// Unsplash API (Server経由)
// ============================================

/**
 * Unsplashから画像を検索
 */
export async function searchImage(query: string): Promise<{
  success: boolean;
  imageUrl?: string;
  source?: 'unsplash' | 'placeholder';
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/unsplash?query=${encodeURIComponent(query)}`);

    if (!response.ok) {
      throw new Error(`Failed to search image: ${response.status}`);
    }

    const data = await response.json();
    return {
      success: true,
      imageUrl: data.imageUrl,
      source: data.source || 'unsplash'
    };
  } catch (error) {
    // フォールバック: placeholder画像を使用
    return {
      success: true,
      imageUrl: `https://picsum.photos/seed/${encodeURIComponent(query)}/400/300`,
      source: 'placeholder'
    };
  }
}

// ============================================
// Flashcards API
// ============================================

export interface Flashcard {
  id?: number;
  word: string;
  meaning: string;
  definition?: string;
  example?: string;
  phonetic?: string;
  imageUrl?: string;
  sourceUrl?: string;
  easeFactor?: number;
  intervalDays?: number;
  repetitions?: number;
  nextReviewAt?: string;
  lastReviewedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface FlashcardInput {
  word: string;
  meaning: string;
  definition?: string;
  example?: string;
  phonetic?: string;
  image_url?: string;
  source_url?: string;
}

/**
 * フラッシュカードを保存
 */
export async function saveFlashcard(flashcard: FlashcardInput): Promise<{
  success: boolean;
  id?: number;
  exists?: boolean;
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/flashcards`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(flashcard),
    });

    const data = await response.json();

    if (response.status === 409) {
      return { success: false, exists: true };
    }

    if (!response.ok) {
      throw new Error(data.error || `Failed to save flashcard: ${response.status}`);
    }

    return { success: true, id: data.id };
  } catch (error) {
    console.error('Failed to save flashcard:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * フラッシュカード一覧を取得
 */
export async function getFlashcards(): Promise<{
  success: boolean;
  data?: Flashcard[];
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/flashcards`);

    if (!response.ok) {
      throw new Error(`Failed to fetch flashcards: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, data: data.data || [] };
  } catch (error) {
    console.error('Failed to fetch flashcards:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * 復習対象のフラッシュカードを取得
 */
export async function getFlashcardsForReview(limit?: number): Promise<{
  success: boolean;
  data?: Flashcard[];
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const url = limit
      ? `${baseUrl}/api/flashcards/review?limit=${limit}`
      : `${baseUrl}/api/flashcards/review`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to fetch review flashcards: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, data: data.data || [] };
  } catch (error) {
    console.error('Failed to fetch review flashcards:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * フラッシュカードの復習結果を記録
 * @param id フラッシュカードID
 * @param quality 回答品質 (0-5: 0=完全に忘れた, 5=完璧に覚えている)
 */
export async function recordReview(id: number, quality: number): Promise<{
  success: boolean;
  nextReviewAt?: string;
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/flashcards/${id}/review`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ quality }),
    });

    if (!response.ok) {
      throw new Error(`Failed to record review: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, nextReviewAt: data.nextReviewAt };
  } catch (error) {
    console.error('Failed to record review:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * フラッシュカードを削除
 */
export async function deleteFlashcard(id: number): Promise<{
  success: boolean;
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/flashcards/${id}`, {
      method: 'DELETE',
    });

    if (!response.ok) {
      throw new Error(`Failed to delete flashcard: ${response.status}`);
    }

    return { success: true };
  } catch (error) {
    console.error('Failed to delete flashcard:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * フラッシュカード統計を取得
 */
export async function getFlashcardStats(): Promise<{
  success: boolean;
  stats?: {
    total: number;
    dueForReview: number;
    mastered: number;
    learning: number;
  };
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/flashcards/stats`);

    if (!response.ok) {
      throw new Error(`Failed to fetch flashcard stats: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, stats: data };
  } catch (error) {
    console.error('Failed to fetch flashcard stats:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// Cambridge Dictionary API (Server経由 - CORS回避)
// ============================================

/**
 * Cambridge辞書で単語を検索
 */
export async function lookupCambridge(word: string): Promise<{
  success: boolean;
  word: string;
  definition?: string;
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/cambridge-dictionary?word=${encodeURIComponent(word)}`);

    if (!response.ok) {
      throw new Error(`Failed to lookup Cambridge: ${response.status}`);
    }

    const data = await response.json();
    return {
      success: true,
      word: data.word,
      definition: data.definition
    };
  } catch (error) {
    return {
      success: false,
      word,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
