/**
 * Server API Client
 * サーバー経由が必要なAPI（DB、秘密キー必要なもの）
 */

import { syncStorage } from '../chrome-storage';

interface Settings {
  apiBaseUrl: string;
}

async function getApiBaseUrl(): Promise<string> {
  const settings = await syncStorage.get<Settings>('settings');
  return settings?.apiBaseUrl || 'http://localhost:3001';
}

// ============================================
// Study Logs API
// ============================================

export interface StudyLog {
  id?: string;
  url: string;
  domain: string;
  pageTitle: string;
  duration: number;
  startedAt: string;
  endedAt: string;
  notes?: string;
}

/**
 * 学習ログを保存
 */
export async function saveStudyLog(log: Omit<StudyLog, 'id'>): Promise<{ success: boolean; id?: string; error?: string }> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/study-logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(log),
    });

    if (!response.ok) {
      throw new Error(`Failed to save study log: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, id: data.id };
  } catch (error) {
    console.error('Failed to save study log:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * 学習ログを取得
 */
export async function getStudyLogs(params?: {
  limit?: number;
  offset?: number;
  startDate?: string;
  endDate?: string;
}): Promise<{ success: boolean; data?: StudyLog[]; error?: string }> {
  try {
    const baseUrl = await getApiBaseUrl();
    const searchParams = new URLSearchParams();

    if (params?.limit) searchParams.set('limit', params.limit.toString());
    if (params?.offset) searchParams.set('offset', params.offset.toString());
    if (params?.startDate) searchParams.set('startDate', params.startDate);
    if (params?.endDate) searchParams.set('endDate', params.endDate);

    const url = `${baseUrl}/api/study-logs${searchParams.toString() ? `?${searchParams}` : ''}`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to fetch study logs: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, data: data.data || [] };
  } catch (error) {
    console.error('Failed to fetch study logs:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// YouTube Captions API
// ============================================

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface CaptionEntry {
  start: number;
  duration: number;
  text: string;
}

/**
 * YouTube動画の字幕トラック一覧を取得
 */
export async function getCaptionTracks(videoId: string): Promise<{
  success: boolean;
  tracks?: CaptionTrack[];
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/captions/${videoId}`);

    if (!response.ok) {
      throw new Error(`Failed to fetch captions: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, tracks: data.tracks };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * YouTube動画の字幕を取得
 */
export async function getCaptions(
  videoId: string,
  languageCode?: string
): Promise<{
  success: boolean;
  captions?: CaptionEntry[];
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const url = languageCode
      ? `${baseUrl}/api/captions/${videoId}?lang=${languageCode}`
      : `${baseUrl}/api/captions/${videoId}`;

    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to fetch captions: ${response.status}`);
    }

    const data = await response.json();
    return { success: true, captions: data.captions };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

// ============================================
// Unsplash API (Server経由)
// ============================================

/**
 * Unsplashから画像を検索
 */
export async function searchImage(query: string): Promise<{
  success: boolean;
  imageUrl?: string;
  source?: 'unsplash' | 'placeholder';
  error?: string
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/unsplash?query=${encodeURIComponent(query)}`);

    if (!response.ok) {
      throw new Error(`Failed to search image: ${response.status}`);
    }

    const data = await response.json();
    return {
      success: true,
      imageUrl: data.imageUrl,
      source: data.source || 'unsplash'
    };
  } catch (error) {
    // フォールバック: placeholder画像を使用
    return {
      success: true,
      imageUrl: `https://picsum.photos/seed/${encodeURIComponent(query)}/400/300`,
      source: 'placeholder'
    };
  }
}

// ============================================
// Cambridge Dictionary API (Server経由 - CORS回避)
// ============================================

/**
 * Cambridge辞書で単語を検索
 */
export async function lookupCambridge(word: string): Promise<{
  success: boolean;
  word: string;
  definition?: string;
  error?: string;
}> {
  try {
    const baseUrl = await getApiBaseUrl();
    const response = await fetch(`${baseUrl}/api/cambridge-dictionary?word=${encodeURIComponent(word)}`);

    if (!response.ok) {
      throw new Error(`Failed to lookup Cambridge: ${response.status}`);
    }

    const data = await response.json();
    return {
      success: true,
      word: data.word,
      definition: data.definition
    };
  } catch (error) {
    return {
      success: false,
      word,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
